name: fsp
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.4.1
  geolocator: ^10.1.0
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  # google_maps: ^8.2.0
  http: ^0.13.6
  google_maps_flutter_platform_interface: ^2.0.4
  flutter_tts: ^3.8.3
  collection: ^1.15.0
  # provider: ^4.0.4

  english_words: ^4.0.0
  provider: ^6.0.0
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^2.5.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/black-grey-chicago-city-area-background-map-vector-37821140.jpg
    - assets/map_style/